### ISSUE TITLE
Doesn't predict the image inserted without save_image's box checked

### ISSUE THREAD

**Issue by Eugenill** [bonastreyair/node-red-contrib-teachable-machine#14]
![image](https://user-images.githubusercontent.com/55345724/83802295-c64fef80-a6aa-11ea-8d2d-1fdb7d6b1025.png)

![image](https://user-images.githubusercontent.com/55345724/83801989-4de92e80-a6aa-11ea-97b7-1bb793569880.png)

![image](https://user-images.githubusercontent.com/55345724/83801937-36aa4100-a6aa-11ea-822f-d0b19452cd10.png)

It seems that when the _save image_ check box is not pressed the prediction returned is not from the image passed, **but from the first image passed with the _save image_ box not checked**.

But once it's pressed, it works:
![image](https://user-images.githubusercontent.com/55345724/83801767-fe0a6780-a6a9-11ea-9468-f1bb6a2a5d8d.png)
![image](https://user-images.githubusercontent.com/55345724/83802094-75d89200-a6aa-11ea-9c4b-d85108882c71.png)

I tried it with the last version of the node: 1.1.2, and with the example provided.

Also tried to modify the other parameters, and nothing changed. 
I haven't yet tried to find the issue on the code itself. 
But it looks like is saving either the prediction of that first image or the image itself and then its prediction is returned.

Thanks Yair!

**Comment by bonastreyair** [comment]
Thanks! This has been solved in [Release 1.1.3](https://github.com/bonastreyair/node-red-contrib-teachable-machine/releases/tag/v1.1.3)
