### ISSUE TITLE
node-red-contrib-teachable-machine:teachable machine : TypeError: Cannot read property 'some' of undefined (line:5)

### ISSUE THREAD

**Issue by bighb69738** [bonastreyair/node-red-contrib-teachable-machine#15]
I hit an error. TypeError: Cannot read property 'some' of undefined (line:5)
Flows stopped due to missing node types, when i deployed the flow .

`
===================

28 Aug 14:14:17 - [info] Node-RED version: v1.1.3
28 Aug 14:14:17 - [info] Node.js  version: v12.18.3
28 Aug 14:14:17 - [info] Darwin 17.7.0 x64 LE
28 Aug 14:14:17 - [info] Loading palette nodes
28 Aug 14:14:18 - [warn] ------------------------------------------------------
28 Aug 14:14:18 - [warn] [node-red-contrib-teachable-machine/teachable machine] TypeError: Cannot read property 'some' of undefined (line:5)
28 Aug 14:14:18 - [warn] ------------------------------------------------------
28 Aug 14:14:18 - [info] Settings file  : /Users/x/.node-red/settings.js
28 Aug 14:14:18 - [info] Context store  : 'default' [module=memory]
28 Aug 14:14:18 - [info] User directory : /Users/x/.node-red
28 Aug 14:14:18 - [warn] Projects disabled : editorTheme.projects.enabled=false
28 Aug 14:14:18 - [info] Flows file     : /Users/x/.node-red/flows_MacBook.local.json
28 Aug 14:14:18 - [info] Server now running at http://127.0.0.1:1880/
28 Aug 14:14:18 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

28 Aug 14:14:18 - [info] Waiting for missing types to be registered:
28 Aug 14:14:18 - [info]  - teachable machine
28 Aug 14:14:33 - [info] Stopping flows
28 Aug 14:14:33 - [info] Stopped flows
28 Aug 14:14:33 - [info] Starting flows
28 Aug 14:14:33 - [info] Started flows
28 Aug 14:14:46 - [info] Uninstalling module: node-red-contrib-teachable-machine
28 Aug 14:14:48 - [info] Uninstalled module: node-red-contrib-teachable-machine
28 Aug 14:14:48 - [info] Removed node types:
28 Aug 14:14:48 - [info]  - node-red-contrib-teachable-machine:teachable machine
28 Aug 14:15:08 - [info] Installing module: node-red-contrib-teachable-machine, version: 1.1.4
28 Aug 14:15:34 - [info] Installed module: node-red-contrib-teachable-machine
28 Aug 14:15:34 - [info] Added node types:
28 Aug 14:15:34 - [info]  **- node-red-contrib-teachable-machine:teachable machine : TypeError: Cannot read property 'some' of undefined (line:5)**
28 Aug 14:16:21 - [info] Stopping flows
28 Aug 14:16:21 - [info] Stopped flows
28 Aug 14:16:21 - [info] Waiting for missing types to be registered:
28 Aug 14:16:21 - [info]  - teachable machine
28 Aug 14:17:19 - [info] Stopping flows
28 Aug 14:17:19 - [info] Stopped flows
28 Aug 14:17:19 - [info] Starting flows
28 Aug 14:17:19 - [info] Started flows
28 Aug 14:30:25 - [info] Stopping flows
28 Aug 14:30:25 - [info] Stopped flows
28 Aug 14:30:25 - [info] Waiting for missing types to be registered:
28 Aug 14:30:25 - [info]  - teachable machine

<img width="924" alt="螢幕快照 2020-08-28 下午2 35 30" src="https://user-images.githubusercontent.com/38970513/91529437-e0ad0880-e93b-11ea-86e0-baebe9fe314b.png">

<img width="852" alt="螢幕快照 2020-08-28 下午2 35 48" src="https://user-images.githubusercontent.com/38970513/91529446-e4408f80-e93b-11ea-8438-8f788ce3c018.png">

**Comment by kazuhitoyokoi** [comment]
I encountered the same problem. After updating the version of `jsdom` module (16.2.2) to the latest (16.4.0), it works correctly.
https://github.com/bonastreyair/node-red-contrib-teachable-machine/blob/v1.1.4/package.json#L8

**Comment by bonastreyair** [comment]
I'll test it and update dependancies if that solves the issue. 

Thanks!

**Comment by bighb69738** [comment]
Thank @kazuhitoyokoi  for your  assistance. 
The problem has been solved.

**Comment by kazuhitoyokoi** [comment]
I'm glad to hear that. :) I also enjoy using this Teachable Machine node!

**Comment by bonastreyair** [comment]
solved on [release 1.1.5](https://github.com/bonastreyair/node-red-contrib-teachable-machine/releases/tag/v1.1.5) npm module should appear in a while tobe able to update it from manage palette.
