### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by starcrouz** [bonastreyair/node-red-contrib-teachable-machine#16]
Hi
Just tried to install from Node-red Manage Pallete on both Pi and Windows but just get this error
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-contrib-teachable-machine - Not found

_Originally posted by @Viggen-l in https://github.com/bonastreyair/node-red-contrib-teachable-machine/issues/11#issuecomment-669833151_

**Comment by starcrouz** [comment]
There is a typo in the NPM URL : is it  https://registry.npmjs.org/node-red-contrib-teachable-machine
and not  https://registry.npmjs.org/node-contrib-teachable-machine
Yes, the difference is "-red"

**Comment by bonastreyair** [comment]
You are totally right! I'll make a modification on the readme. Thanks!

Regarding the raspberry it is yet not compatible, check the opened issues.
