### ISSUE TITLE
tfjs version (again :-)

### ISSUE THREAD

**Issue by dceejay** [bonastreyair/node-red-contrib-teachable-machine#18]
Hi

back in the Issue #8 we had fun with myself wanting tfjs version 1.4.0 - and teachable machines requiring 1.3.1 for the image pre-req.... now that that has been removed :-)... can we bump the tfjs lib to be 1.4.0 also ?

I have pinned to this level as it seems to be the last one that just installs clean on Pi as-is - there are newer versions both in 1.x branch and 2.x - but they all need manual recompile to make work on Pi which is a pain for most users. (me included). Having both our libs in sync means both nodes can operate at the same time (if necessary) much more interchangeably.

Thanks again

**Comment by bonastreyair** [comment]
Sure I'll revert it to v1.4.0 "again :-)" when I have some spare time. I'll let you know as soon as possible!

**Comment by bonastreyair** [comment]
Done! @dceejay hope now is fine for Raspberry Pi users! 😄

**Comment by dceejay** [comment]
excellent - many thanks.
