### ISSUE TITLE
Add Model reload

### ISSUE THREAD

**Issue by acejacek** [bonastreyair/node-red-contrib-teachable-machine#22]
Proposed enhancement: trigger model reload. Now it's impossible (?) to reload model. The workaround is to disable and reenable the node. It would be perfect to be able to automatize it.

**Comment by bonastreyair** [comment]
Yeah that is a great idea! Thanks for the PR! Let me check on it and add it! Cool!

**Comment by bonastreyair** [comment]
v1.3.0 published on [npm](https://www.npmjs.com/package/node-red-contrib-teachable-machine/v/1.3.0)
