### ISSUE TITLE
loading model error

### ISSUE THREAD

**Issue by dceejay** [bonastreyair/node-red-contrib-teachable-machine#3]
Hi 
thanks for the awesomeness.

I'm getting this loading error 
```
TypeError: response.arrayBuffer is not a function
    at /Users/conway/.node-red/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:97:90
    at Array.map (<anonymous>)
...
```

which I fixed in my node by

https://github.com/dceejay/tfjs-coco-ssd/blob/master/tfjs.js#L8

**Comment by bonastreyair** [comment]
Without the `global.` in the `fetch` variable I did´t have any problems even using MacOSX, Windows10 or Ubuntu. I used a fresh installed `npm`, `node.js` and `Node-RED v1.0.5` for the tests.

With this patch it works for me anyway so I hope this can solve this issue to others that try the node.

I don´t understand how it can work for me without global though. Can you tell me if with just this change it solves the issue? If it does I will upload a new version.

Thanks!

**Comment by dceejay** [comment]
Hi - likewise I'm not sure why it is necessary - and for me sometimes it loaded ok (on Mac) - but then once it fails (again on Mac) it seems to start "broken" so maybe some timing edge case or some odd scoping issue - but hey so far - as you said I can't see any downside so thanks.
