### ISSUE TITLE
Inferencing RPi does not work

### ISSUE THREAD

**Issue by naguelfar** [bonastreyair/node-red-contrib-teachable-machine#45]
Hi,

I tried your plugin on node red 2.2 on my RPI, but it still waiting in "inferencing" when I upload an image (simple cat / dog categorisation).

I tried the same flow on docker (mac) and it's ok.

**Comment by bonastreyair** [comment]
Are you using docker in RPi also? 
Can you post the error Node-RED logs out? Thanks!

**Comment by naguelfar** [comment]
Docker is only use on my mac.
I did'nt find any log (via node-red-log with trace level nothing appear). Is their another way ?

**Comment by naguelfar** [comment]
Ok i've found a solution. I've deleted tfjs-core and tfjs-node from packages.json

Now it's ok.
