### ISSUE TITLE
Valid model is "is not ready" 

### ISSUE THREAD

**Issue by guillad** [bonastreyair/node-red-contrib-teachable-machine#5]
First of all, Great Work!

When using this valid model, to classify bananas: 
https://teachablemachine.withgoogle.com/models/38NDc7ERE/

the debugger says: "**`model is not ready`**"
 (in the flow it's: "model not loaded").

Is it fixable? here's my flow:

`[{"id":"c66a85b7.e30d58","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"c4b4bcdf.7a551","type":"teachable machine","z":"c66a85b7.e30d58","name":"","modelUrl":"teachablemachine.withgoogle.com/models/38NDc7ERE/","output":"all","x":610,"y":260,"wires":[["7c484b9f.b58544"]]},{"id":"a9c665cb.3d9dc8","type":"image","z":"c66a85b7.e30d58","name":"","width":160,"data":"payload","dataType":"msg","thumbnail":false,"active":true,"x":600,"y":420,"wires":[]},{"id":"cc300434.61c488","type":"fileinject","z":"c66a85b7.e30d58","name":"","x":360,"y":320,"wires":[["c4b4bcdf.7a551","a9c665cb.3d9dc8"]]},{"id":"7c484b9f.b58544","type":"debug","z":"c66a85b7.e30d58","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":850,"y":340,"wires":[]}]`
![image](https://user-images.githubusercontent.com/57844677/79063742-1e223980-7cac-11ea-9671-a1c9851c4114.png)

Thanks!

**Comment by bonastreyair** [comment]
Be aware to put `https://` at the begining of your URL, it works for me when changed to. 

![Screenshot 2020-04-12 at 14 48 32](https://user-images.githubusercontent.com/37800834/79069205-c1834680-7ccc-11ea-9ad6-4a2c6f51cace.png)

I will make a patch that will enable the URL to work with or without `https://`
Thanks!
