### ISSUE TITLE
TypeError: engine_1.ENGINE.makeTensor is not a function

### ISSUE THREAD

**Issue by guillad** [bonastreyair/node-red-contrib-teachable-machine#7]
Hi @bonastreyair,

Followed the new insructions of version 0.1.3, but when using the [basic.json example](https://github.com/bonastreyair/node-red-contrib-teachable-machine/blob/master/examples/basic.json)  I get now:

"`TypeError: engine_1.ENGINE.makeTensor is not a function`"

I'm using Windows 10 installation with all the pre-requisites. Also, the [node-red-contrib-tfjs-coco-ssd](https://github.com/dceejay/tfjs-coco-ssd/) node is working fine on my environment.

Thanks!

**Comment by bonastreyair** [comment]
I think that you may have a version problem of the `@tensorflow/tfjs`. I once had this problem and I think you may have installed another version and it is having a problem. Can you check if you can install in the `~/.node-red` the correct version of `tfjs`? 

You can use this command:
```
npm install @tensorflow/tfjs@1.3.1
```
Does it appear any `npm WARN` while installing?

Afterwards can you check the installed versions using `npm list` in `~/.node-red/npm-modules/`. You should see something like this. All `@tensorflow` dependancy modules should be `@1.3.1`.

![Screenshot 2020-04-13 at 11 47 26](https://user-images.githubusercontent.com/37800834/79111302-8dfff500-7d7c-11ea-96d5-d210f572268d.png)

**Comment by guillad** [comment]
Thanks @bonastreyair,

I've followed your guidelines and [this forum as well](https://github.com/justadudewhohacks/face-api.js/issues/455)
1. installed `tfjs@1.3.1` with no warnings
2. npm list in ~/.node-red/node_modules/ with almost identical results
![image](https://user-images.githubusercontent.com/57844677/79112752-fb655300-7d87-11ea-91a2-f7b4b443f2e3.png)
3. I get now this error from cmd:
`[error] [teachable machine:c4b4bcdf.7a551] model is not ready`

Likewise, I think it's envirmental problem from my end.
Thanks for the effort!

**Comment by bonastreyair** [comment]
But does it show any other error apart from "model is not ready", so that we can investigate what is the problem?

Are you using node v10?

**Comment by guillad** [comment]
Now it's almost working :-)
I finally get the green dot indicating model is loaded successfully. 
![image](https://user-images.githubusercontent.com/57844677/79121891-09729e00-7d9f-11ea-859a-5ec747f9d8b7.png)

Here's what I did:
1. uninstalled&reinstalled completely everything including node.js, node-red and python. 
2. Upgraded node-red from `node-red@1.0.4` to `node-red@1.0.5` on Windows 10. 
3. Installed `npm install @tensorflow/tfjs@1.3.1` and `npm install @tensorflow/tfjs-node`
3. installed again the `node-red-contrib-teachable-machine@0.1.3` node, and 
4. retrained the TM model, with different URL. 

Now, when processing the model (infering status), I get this log.  

```
(node:3448) UnhandledPromiseRejectionWarning: TypeError: engine_1.ENGINE.makeTensor is not a function
    at makeTensor (C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\ops\tensor_ops.js:97:28)
    at Object.scalar (C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\ops\tensor_ops.js:126:12)
    at C:\Users\Giladl\.node-red\node_modules\@teachablemachine\image\dist\utils\tf.js:34:46
    at C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs-core\dist\engine.js:349:22
    at Engine.scopedRun (C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs-core\dist\engine.js:359:23)
    at Engine.tidy (C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs-core\dist\engine.js:348:21)
    at Object.tidy (C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\globals.js:176:28)
    at Object.capture (C:\Users\Giladl\.node-red\node_modules\@teachablemachine\image\dist\utils\tf.js:26:15)
    at C:\Users\Giladl\.node-red\node_modules\@teachablemachine\image\dist\custom-mobilenet.js:288:49
    at C:\Users\Giladl\.node-red\node_modules\@tensorflow\tfjs-core\dist\engine.js:349:22
(node:3448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by guillad** [comment]
Ok, Now it's totally working!

I think installing the latest tfjs packages (1.7.2) made the change:
```
npm install @tensorflow/tfjs-node@1.7.2
npm install @tensorflow/tfjs-core@1.7.2
npm install @tensorflow/tfjs-data@1.7.2
npm install @tensorflow/tfjs-layers@1.7.2
npm install @tensorflow/tfjs-converter@1.7.2

```
![image](https://user-images.githubusercontent.com/57844677/79124629-683b1600-7da5-11ea-8596-6b385c45cd77.png)


Thanks again, This issue can be closed I guess...

**Comment by bonastreyair** [comment]
I'm glad you can finally make it work installing latests versions `@tensorflow/tfjs-node@1.7.2`! Using MacOSX and this version you comment doesn't work. Also `@teachablemachine/image` uses `@tensorflow/tfjs-node@1.3.1` that's why I stick with this version.

I think that in some way you had some older versions that were in conflict with `@tensorflow/tfjs-node@1.3.1 ` and after upgrading to `@tensorflow/tfjs-node@1.7.2` those older versions got removed so now the package can use the ones installed in `@tensorflow/tfjs-node@1.3.1 `.

For next time, when having trouble with installed nodes, instead of reinstalling everything, what you can just do is the following
1. Close `Node-RED`
2. Remove the `node-modules` folder using this Linux commands
```
cd ~/.node-red
rm -r node-modules
```
**Note:** This will delete all your additional installed nodes in Node-RED but it cleans whatever you have installed

- Option a) Open `Node-RED` and reinstall via Manage Package
- Option b) Install again the m

You have to be careful with installing global `npm modules`, if you have them installed, it can make incompatibilities with Node-RED.

I'm closing the issue.
