### ISSUE TITLE
Another loading issue

### ISSUE THREAD

**Issue by dceejay** [bonastreyair/node-red-contrib-teachable-machine#8]
hi - I'm now getting another model loading issue
```
13 Apr 13:56:56 - [error] [teachable machine:3adcecf5.19a6e4] TypeError: response.arrayBuffer is not a function
TypeError: response.arrayBuffer is not a function
    at /Users/fred/.node-red/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:97:90
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/fred/.node-red/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:97:48)
    at step (/Users/fred/.node-red/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:48:23)
    at Object.next (/Users/fred/.node-red/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:29:53)
    at fulfilled (/Users/fred/.node-red/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

If I update the tfjs-node library locally to ~1.4.0 the issue goes away.
(this is the same level as I use in the coco-ssd node - no idea if that's related in any way)

**Comment by bonastreyair** [comment]
So weird... I still totally not understand how `npm` works at 100%, but I'm sure that with a clean installation of `@tensorflow/tfjs-node@1.3.1` it works. But it seems like if you have other versions installed it can make a problem... 

 - issue #7 was solved installing `@tensorflow/tfjs-node@1.7.2`, which it doesn't make sense to me why.

I just let `@tensorflow/tfjs-node@1.3.1` since it is one of the dependancies from `teachablemachine/image@0.8.4`.

Whats your recommendation on what to do in this cases?

**Comment by dceejay** [comment]
hmm - good question.
I stuck with 1.4.0 as anything more recent then didn't install correctly on a Pi in a single step.

Turns out you need to do extra manual steps -  as per https://github.com/yhwang/node-red-contrib-tf-model#note - to get the device specific parts to work. - so it sort of depends....
either we can pick 1.4 as default - (which is a bit lame as no doubt there will be useful fixes getting added) - or have to somehow get a two step install to work...  in which case then 1.7 would be best etc.

I have asked yhwang if they could potentially do it automatically as a pre-install script... If not maybe we have to :-(

So I think 1.4 for now and see what we can all come up with to improve the install experience.

**Comment by guillad** [comment]
Hi guys, 
after a short research on my Windows10, and a fresh installation of the latest:
**node.js@12.16.2**, **npm@6.14.4** (`node --version && npm --version`)
**node-red@1.0.5**,  **tfjs@1.7.2,  @tensorflow/tfjs-node@1.7.2,  @tensorflow/tfjs-core@1.7.2,  @tensorflow/tfjs-data@1.7.2,  @tensorflow/tfjs-layers@1.7.2,  @tensorflow/tfjs-converter@1.7.2**

I've found that node-red-contrib-teachable-machine@0.1.3 and[ node-red-contrib-tfjs-coco-ssd@0.3.2](https://flows.nodered.org/node/node-red-contrib-tfjs-coco-ssd) are **conflicting each other**, and only after uninstalling either of these nodes, the other works great. I can share an example flow if needed. 

This coexistence issue is also happening with another tensorflow.js node:
[node-red-contrib-face-recognition@1.3.3](https://flows.nodered.org/node/node-red-contrib-face-recognition)

Maybe the conclusion is a versioning issue and they all need to be upgraded to the latest tfjs version? (currently 1.7.2)

**Comment by dceejay** [comment]
if only was that simple... the teachable machines library seem to require a peer of 1.3.   my coco-ssd node prefers 1.4 as that loads models correctly on Pi (whereas 1.3 didn't) - and 1.5 onwards have dropped built in support for Pi and Jetson nano etc and need to be manually patched after install... So all a bit of a mess at the moment.

**Comment by dceejay** [comment]
ok  - have tried this node using 1.4 and it seems to load ok (so far) - so that does then allow both this and my coco ssd node to co-exist. Any chance you can bump the require in the package.json and try it locally your side to check ?

**Comment by bonastreyair** [comment]
Sure, I’ll check it on my side and if it works, I can bump it to `v1.4.0`. Just to mention that then some warnings in the `npm` will appear due to the `teachablemachine/image` dependency to `v1.3.1`.

**Comment by bonastreyair** [comment]
That is what I get when using `v1.4.0`. 

`npm WARN @teachablemachine/image@0.8.4 requires a peer of @tensorflow/tfjs@1.3.1 but none is installed. You must install peer dependencies yourself.`

![Screenshot 2020-04-22 at 18 24 21](https://user-images.githubusercontent.com/37800834/80014280-5d346400-84d0-11ea-9604-c33927a11dac.png)

Apart from the warning, it works fine on my side so I will make the change available with the next release so that they can co-exist together.

**Comment by bonastreyair** [comment]
`v1.1.0` is on its way! I'm closing this issue.
